spring:

  # Spring JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000

  # does this replace application.properties?
  logging:
    level:
      - ".=info"
      - "at.sbaresearch.mqtt4android=debug"

mqtt:
  hostname: "10.0.2.2"

ssl:
  keyStore: "cert-stores/keystore.jks"
  keyStorePassword: "ub1Uwei8"
  trustStore: "cert-stores/keystore_clients.jks"
  trustStorePassword: "ub1Uwei8"
  caKeyAlias: "server"
